name: Node.js CI/CD

on: 
  push:
    branches:
      - main

jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' 
      
      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  test: 
    name: Test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'
        
        - name: Install dependencies
          run: npm install

        - name: Check JavaScript syntax
          run: node --check src/index.js